id: 366
title: Europa Universalis IV Savegame Editor
status: active
type: utility
primary_language: python
languages:
  - python
tags:
  - cli
  - editor
  - eu4
  - europa-universalis-iv
  - python
  - savegame
  - savegame-editor
libraries:
  python:
    - argparse
    - collections
    - dataclasses
    - os
    - pathlib
    - sys
    - winreg
github:
  owner: Knarkoffer
  repo: eu4-savegame-editor
